set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=$HOME/vimfiles/bundle/Vundle.vim/
call vundle#begin('$USERPROFILE/vimfiles/bundle/')

Plugin 'VundleVim/Vundle.vim'   " let Vundle manage Vundle, required

" Colorschemes
Plugin 'flazz/vim-colorschemes'

Plugin 'jelera/vim-javascript-syntax', {'autoload':{'filetypes':['javascript']}}
Plugin 'mattn/emmet-vim', {'autoload':{'filetypes':['html', 'css']}}

Plugin 'bling/vim-airline'

Plugin 'kien/ctrlp.vim'

Plugin 'sheerun/vim-polyglot'
Plugin 'tikhomirov/vim-glsl'
Plugin 'pangloss/vim-javascript'
Plugin 'scrooloose/syntastic'

Plugin 'scrooloose/nerdtree'

Plugin 'tpope/vim-surround'
Plugin 'Raimondi/delimitMate'
Plugin 'ntpeters/vim-better-whitespace'

Plugin 'xolox/vim-misc'
Plugin 'xolox/vim-colorscheme-switcher'

call vundle#end()            " required
" filetype plugin indent on    " required

" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
" Put your non-Plugin stuff after this line

set wildignore+=*.swp,*.zip,*.exe,*.min.js,*.min.css,*.png,*.jpg,*.jpeg,*.psd
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe

if has("gui")
	" Open gvim maximized
	au GUIEnter * simalt ~x
endif

" ==== Plugin configuration

" Vim airline
let g:airline_section_b = '%{getcwd()}'
let g:airline_section_c = '%t'

" NERDTree
autocmd BufEnter * lcd %:p:h
let NERDTreeChDirMode=0

" Auto close brackets
let delimitMate_expand_cr = 1

" Remove Whitespace on save
let g:strip_whitespace_on_save=1

" Emmet
let g:user_emmet_leader_key='<C-z>'

" ==== Others

let mapleader = ","
let maplocalleader = "\\"

"Useful shortcuts
noremap <leader>n :NERDTreeToggle<CR>
nnoremap <leader>ev :vsplit $MYVIMRC<CR>

set backspace=indent,eol,start
if has("multi_byte")
	if &termencoding == ""
		let &termencoding = &encoding
	endif
	set encoding=utf-8
	setglobal fileencoding=utf-8
	set fileencodings=ucs-bom,utf-8,latin1
	set ffs=unix,dos,mac
endif

"history and error sounds
set history=1000
set undolevels=1000
set visualbell
set noerrorbells
" Turn backup off, since most stuff is in SVN, git et.c anyway...
set nobackup
set nowb
set noswapfile

"Setting the indentation width to 4, because fuck yes! And also making the indentation smart
set tabstop=4 softtabstop=4 shiftwidth=4 noexpandtab
set autoindent smartindent copyindent smarttab
set ignorecase "ignore case when searching
set showmatch "show matching paranthesis
set smartcase "ignore case if all lower case, otherwise case sensitive

"list specific chars
set list
set listchars=tab:¦\ \,trail:.,extends:#,nbsp:.

"Paragraph formatting
vnoremap <leader>Q gq
nnoremap <leader>Q gqap

" Vim is running in a GUI
if has("gui_running")
	set lines=999 columns=999

    set guiheadroom=0

	"Beautifulness
	colorscheme seoul256
	colorscheme mustang
	colorscheme badwolf
	"colorscheme VIvid

	noremap <F2> :colorscheme tangoshady<CR>

	syntax on

    set guioptions-=m  "remove menu bar
    set guioptions-=T  "remove toolbar
	set guioptions-=l guioptions-=L guioptions-=r guioptions-=R "remove scrollbars
endif

"SPLIT PANES
noremap <leader>v <C-w>v
noremap <leader>s <C-w>s
noremap <leader>h <C-w>h
noremap <leader>j <C-w>j
noremap <leader>k <C-w>k
noremap <leader>l <C-w>l
"Open new panes to the bottom and the right
set splitbelow splitright

"GUI settings
set wildmenu
set ruler
set guifont=Lucida_Console:h10

"Editor
set hlsearch
set incsearch
"Show linenumbers because that's always useful
set nu

"Wordwrapping settings
set nowrap linebreak

"Move up and down regardless of wordwrapping
noremap j gj
noremap k gk

"Getting rid of bad habits..
"Change the ESC map
"Remove support for arrowkeys, learn the hard way ;)
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
inoremap <esc> <NOP>
inoremap jk <esc>

" move lines up and down, for each mode
" source: http://vim.wikia.com/wiki/Moving_lines_up_or_down
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
inoremap <A-j> <Esc>:m .+1<CR>==gi
inoremap <A-k> <Esc>:m .-2<CR>==gi
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv

" Close the current buffer and switch to the previous
" without closing the current window
:command! Bc bprevious | bdelete #

" Status line
set laststatus=2

" Autocommands
" Remove Trailing Whitespaces on save for all files
autocmd BufWritePre <buffer> :%s/\s\+$//e

autocmd BufWinLeave ?* if expand("%") != "" | mkview | endif
autocmd BufWinEnter,BufRead ?* if expand("%") != "" | silent loadview | endif

autocmd! BufWinEnter,BufNewFile,BufRead *.vs,*.fs set filetype=glsl

autocmd! bufwritepost _vimrc source %

iabbrev cat >^.^<
